server:
  port: 8082

spring:
  application:
    name: project-service
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/